driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    run_list: yum::default
  

suites:
  - name: default
    run_list:
      - recipe[flugel-grafana-prometheus::default]
    attributes:
